version: "3"

services:
  localhost:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  frontend:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - localhost
